### ISSUE TITLE
关于1.java反射机制.md烦请解惑

### ISSUE THREAD

**Issue by hahaSec** [Maskhe/javasec#1]
![image](https://user-images.githubusercontent.com/20596600/79452985-9d509e00-801b-11ea-9fd4-a572ce134c73.png)
在阅读到这里的时候，发现作者对invoke方法的理解和我的理解存在误差。
我认为invoke的第一个参数传的是一个类的对象，并不是一个方法对象。。还请解惑，谢谢。

**Comment by Maskhe** [comment]
没有问题，你仔细读读我写的，确实是一个类的对象，但是 是&nbsp;&nbsp; 即将要调用这个方法的&nbsp; 的对象


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hahaSec"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月16日(星期四) 晚上7:54
收件人:&nbsp;"Maskhe/javasec"<javasec@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Maskhe/javasec] 关于1.java反射机制.md烦请解惑 (#1)





 

 在阅读到这里的时候，发现作者对invoke方法的理解和我的理解存在误差。
 我认为invoke的第一个参数传的是一个类的对象，并不是一个方法对象。。还请解惑，谢谢。
